// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK_cB8Ufp1xYyn0njx4XdU0jhx1yV2yc0',
    appId: '1:946382156387:web:6dd520d7911c5e93efbe56',
    messagingSenderId: '946382156387',
    projectId: 'savo-1529a',
    authDomain: 'savo-1529a.firebaseapp.com',
    storageBucket: 'savo-1529a.firebasestorage.app',
    measurementId: 'G-SVT6TKVKSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArkNkQ47qI3dBe-52pYvvYlFUFRWDO-H0',
    appId: '1:946382156387:android:ff283f96e6fd5d23efbe56',
    messagingSenderId: '946382156387',
    projectId: 'savo-1529a',
    storageBucket: 'savo-1529a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAkNeyF3jKSJ67LPOiKH6uqYCT5Ql6mkE',
    appId: '1:946382156387:ios:5242ed21aa3b3678efbe56',
    messagingSenderId: '946382156387',
    projectId: 'savo-1529a',
    storageBucket: 'savo-1529a.firebasestorage.app',
    iosBundleId: 'com.example.savo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAkNeyF3jKSJ67LPOiKH6uqYCT5Ql6mkE',
    appId: '1:946382156387:ios:5242ed21aa3b3678efbe56',
    messagingSenderId: '946382156387',
    projectId: 'savo-1529a',
    storageBucket: 'savo-1529a.firebasestorage.app',
    iosBundleId: 'com.example.savo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK_cB8Ufp1xYyn0njx4XdU0jhx1yV2yc0',
    appId: '1:946382156387:web:88a8f4f51d4f9e74efbe56',
    messagingSenderId: '946382156387',
    projectId: 'savo-1529a',
    authDomain: 'savo-1529a.firebaseapp.com',
    storageBucket: 'savo-1529a.firebasestorage.app',
    measurementId: 'G-5RVLGEC68D',
  );
}
